apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ukrajina
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ukrajina
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ukrajina
    newTag: 'latest'
