apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ua
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ua
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ua
    newTag: 'b8182d7c0a807fc7b4b5108aa0c2ea6f4bcecc66'
