apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ua
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ua
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ua
    newTag: 'b2a7255ba90489e58b84138f718fe179806b0c1a'
