apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ukraine
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ukraine
    newTag: 'latest'
